import { CareElementListItemType } from "../../../../../types/api";

export const careElementsList: CareElementListItemType[] = [
  {
    name: "Smoking Status (Y/N)",
    key: "SmokingStatus",
    valueKey: "Status",
    unitKey: "",
    unit: "",
  },
  {
    name: "Smoking packs (per day)",
    key: "SmokingPacks",
    valueKey: "PerDay",
    unitKey: "",
    unit: "packs per day",
  },
  {
    name: "Weight (kg)",
    key: "Weight",
    valueKey: "Weight",
    unitKey: "WeightUnit",
    unit: "kg",
  },
  {
    name: "Weight (lbs)",
    key: "Weight",
    valueKey: "Weight",
    unitKey: "WeightUnit",
    unit: "lbs",
  },
  {
    name: "Height (cm)",
    key: "Height",
    valueKey: "Height",
    unitKey: "HeightUnit",
    unit: "cm",
  },
  {
    name: "Height (ft in)",
    key: "Height",
    valueKey: "Height",
    unitKey: "HeightUnit",
    unit: "ft in",
  },
  {
    name: "Body Mass Index (kg/m2)",
    key: "bodyMassIndex",
    valueKey: "BMI",
    unitKey: "",
    unit: "kg/m2",
  },
  {
    name: "Body Surface Area (m2)",
    key: "bodySurfaceArea",
    valueKey: "BSA",
    unitKey: "",
    unit: "m2",
  },
  {
    name: "Waist Circumference (cm)",
    key: "WaistCircumference",
    valueKey: "WaistCircumference",
    unitKey: "WaistCircumferenceUnit",
    unit: "cm",
  },
  {
    name: "Systolic (mmHg)",
    key: "BloodPressure",
    valueKey: "SystolicBP",
    unitKey: "BPUnit",
    unit: "mmHg",
  },
  {
    name: "Diastolic (mmHg)",
    key: "BloodPressure",
    valueKey: "DiastolicBP",
    unitKey: "BPUnit",
    unit: "mmHg",
  },
  {
    name: "E2 (pmol/L)",
    key: "E2",
    valueKey: "E2",
    unitKey: "E2Unit",
    unit: "pmol/L",
  },
  {
    name: "LH (IU/L)",
    key: "LH",
    valueKey: "LH",
    unitKey: "LHUnit",
    unit: "IU/L",
  },
  {
    name: "P4 (ng/mL)",
    key: "P4",
    valueKey: "P4",
    unitKey: "P4Unit",
    unit: "ng/mL",
  },
  {
    name: "FSH (IU/L)",
    key: "FSH",
    valueKey: "FSH",
    unitKey: "FSHUnit",
    unit: "IU/L",
  },
  {
    name: "AMH (pmol/L)",
    key: "AMH",
    valueKey: "AMH",
    unitKey: "AMHUnit",
    unit: "pmol/L",
  },
  {
    name: "DHEAS (umol/L)",
    key: "DHEAS",
    valueKey: "DHEAS",
    unitKey: "DHEASUnit",
    unit: "umol/L",
  },
  {
    name: "HCG (IU/L)",
    key: "HCG",
    valueKey: "HCG",
    unitKey: "HCGUnit",
    unit: "IU/L",
  },
  {
    name: "PRL (ng/mL)",
    key: "PRL",
    valueKey: "PRL",
    unitKey: "PRLUnit",
    unit: "ng/mL",
  },
  {
    name: "TSH (mIU/L)",
    key: "TSH",
    valueKey: "TSH",
    unitKey: "TSHUnit",
    unit: "mIU/L",
  },
  {
    name: "Testosterone (nmol/L)",
    key: "Testosterone",
    valueKey: "Testosterone",
    unitKey: "TestosteroneUnit",
    unit: "nmol/L",
  },
];
