import {
  CycleType,
  DemographicsType,
  SiteFormType,
  StaffFormType,
  StaffType,
} from "../../types/api";
import { nowTZTimestamp } from "../dates/formatDates";

export const initialSite: SiteFormType = {
  name: "",
  address: "",
  postal_code: "",
  zip_code: "",
  province_state: "",
  city: "",
  phone: "",
  fax: "",
  logo: null,
  rooms: [],
  created_by_id: 0,
  date_created: nowTZTimestamp(),
  email: "",
  site_status: "Open",
};

export const initialCycle = (
  demographicsInfos: DemographicsType,
  staffInfos: StaffType[]
): Partial<CycleType> => ({
  cycle_length: "",
  menstruation_length: "",
  etiology: "",
  amh: "",
  partner_sperm: true,
  donor_sperm_nbr: "",
  lmp: null,
  ohip_funded: false,
  cancelled: false,
  cycle_type: "",
  third_party: "",
  prewash_concentration: "",
  prewash_motility: "",
  postwash_motility: "",
  postwash_total_motile_sperm: "",
  test_blood_type_female: "",
  test_blood_type_male: "",
  test_hiv_female: "",
  test_hiv_male: "",
  test_hep_b_female: "",
  test_hep_b_male: "",
  test_hep_c_female: "",
  test_hep_c_male: "",
  test_syphilis_female: "",
  test_syphilis_male: "",
  test_cmv_female: "",
  test_cmv_male: "",
  test_sonohysterogram_female: "",
  test_endo_bx_female: "",
  patient_id: demographicsInfos.patient_id,
  cycle_nbr: "",
  events: [],
  notes: [],
  cycle_notes: "",
  status: "Active",
  site_id:
    staffInfos.find(({ id }) => id === demographicsInfos.assigned_staff_id)
      ?.site_id ?? 0,
  tbr_md: true,
  rwd_md: false,
  tbr_nurse: true,
  rwd_nurse: false,
});

export const initialStaff: StaffFormType = {
  email: "",
  first_name: "",
  middle_name: "",
  last_name: "",
  full_name: "",
  gender: "Male",
  title: "Doctor",
  speciality: "",
  subspeciality: "",
  licence_nbr: "",
  access_level: "staff",
  account_status: "Active",
  cell_phone: "",
  backup_phone: "",
  video_link: "",
  sign: null,
  ai_consent: true,
  ohip_billing_nbr: "",
  date_created: nowTZTimestamp(),
  created_by_id: 0,
  site_id: 0,
};
