export const relations = [
  "Aunt - maternal",
  "Aunt - paternal",
  "Boyfriend",
  "Brother",
  "Cousin - maternal",
  "Cousin - paternal",
  "Daughter",
  "Father",
  "Friend",
  "Girlfriend",
  "Granddaughter - maternal",
  "Grandson - maternal",
  "Granddaughter - paternal",
  "Grandson - paternal",
  "Grandfather - maternal",
  "Grandfather - paternal",
  "Grandmother - maternal",
  "Grandmother - paternal",
  "Half-brother",
  "Half-sister",
  "Husband",
  "Mother",
  "Nephew - maternal",
  "Nephew - paternal",
  "Niece - maternal",
  "Niece - paternal",
  "Sister",
  "Son",
  "Uncle - maternal",
  "Uncle - paternal",
  "Wife",
];
