import { CodeTableType } from "../types/app";

export const namePrefixCT = [
  //CT-001
  { code: "Bro", name: "Brother" },
  { code: "Capt", name: "Captain" },
  { code: "Chief", name: "Chief" },
  { code: "Cst", name: "Constable" },
  { code: "Corp", name: "Corporal" },
  { code: "Dr", name: "Doctor" },
  { code: "Fr", name: "Father" },
  { code: "Hon", name: "Honourable" },
  { code: "Lt", name: "Lieutenant" },
  { code: "Madam", name: "Madam" },
  { code: "Mme", name: "Madame" },
  { code: "Mlle", name: "Mademoiselle" },
  { code: "Major", name: "Major" },
  { code: "Mayor", name: "Mayor" },
  { code: "Miss", name: "Miss" },
  { code: "Mr", name: "Mister" },
  { code: "Mssr", name: "Monsieur" },
  { code: "Mrs", name: "Mrs" },
  { code: "Ms", name: "Ms" },
  { code: "Prof", name: "Professor" },
  { code: "Reeve", name: "Reeve" },
  { code: "Rev", name: "Reverend" },
  { code: "RtHon", name: "Right Honourable" },
  { code: "Sen", name: "Senator" },
  { code: "Sgt", name: "Sergeant" },
  { code: "Sr", name: "Sister" },
];

export const nameSuffixCT: CodeTableType[] = [
  //CT-005
  { code: "Jr", name: "Junior" },
  { code: "Sr", name: "Senior" },
  { code: "II", name: "The Second" },
  { code: "III", name: "The Third" },
  { code: "IV", name: "The Fourth" },
];

export const genderCT: CodeTableType[] = [
  //CT-006
  { code: "M", name: "Male" },
  { code: "F", name: "Female" },
  { code: "O", name: "Other" },
  { code: "U", name: "Unknown" },
];

export const officialLanguageCT: CodeTableType[] = [
  //CT-007
  { code: "ENG", name: "English" },
  { code: "FRE", name: "French" },
];

export const personStatusCT: CodeTableType[] = [
  //CT-008
  { code: "A", name: "Active" }, //patient is part of the practice
  { code: "I", name: "Inactive" },
  { code: "D", name: "Deceased" },
];

export const enrollmentStatusCT: CodeTableType[] = [
  //CT-009
  { code: "1", name: "Enrolled" }, //patient enrolled to a physician
  { code: "0", name: "Not Enrolled" },
];

export const adressTypeCT: CodeTableType[] = [
  //CT-011
  { code: "M", name: "Mailing" },
  { code: "R", name: "Residential" },
];

export const _phoneNumberTypeCT: CodeTableType[] = [
  //CT-012
  { code: "R", name: "Residence" },
  { code: "C", name: "Cellular/Mobile" },
  { code: "W", name: "Work" },
];

export const provinceStateTerritoryCT: CodeTableType[] = [
  //CT-013
  { code: "CA-AB", name: "Alberta" },
  { code: "CA-BC", name: "British Columbia" },
  { code: "CA-MB", name: "Manitoba" },
  { code: "CA-NB", name: "New Brunswick" },
  { code: "CA-NL", name: "Newfoundland" },
  { code: "CA-NS", name: "Nova Scotia" },
  { code: "CA-NT", name: "Northwest Territories" },
  { code: "CA-NU", name: "Nunavut" },
  { code: "CA-ON", name: "Ontario" },
  { code: "CA-PE", name: "Prince Edward Island" },
  { code: "CA-QC", name: "Quebec" },
  { code: "CA-SK", name: "Saskatchewan" },
  { code: "CA-YT", name: "Yukon Territory" },
  { code: "US-AK", name: "Alaska" },
  { code: "US-AL", name: "Alabama" },
  { code: "US-AR", name: "Arkansas" },
  { code: "US-AZ", name: "Arizona" },
  { code: "US-CA", name: "California" },
  { code: "US-CO", name: "Colorado" },
  { code: "US-CT", name: "Connecticut" },
  { code: "US-CZ", name: "Canal Zone" },
  { code: "US-DC", name: "District of Columbia" },
  { code: "US-DE", name: "Delaware" },
  { code: "US-FL", name: "Florida" },
  { code: "US-GA", name: "Georgia" },
  { code: "US-GU", name: "Guam" },
  { code: "US-HI", name: "Hawaii" },
  { code: "US-IA", name: "Iowa" },
  { code: "US-ID", name: "Idaho" },
  { code: "US-IL", name: "Illinois" },
  { code: "US-IN", name: "Indiana" },
  { code: "US-KS", name: "Kansas" },
  { code: "US-KY", name: "Kentucky" },
  { code: "US-LA", name: "Louisiana" },
  { code: "US-MA", name: "Massachusetts" },
  { code: "US-MD", name: "Maryland" },
  { code: "US-ME", name: "Maine" },
  { code: "US-MI", name: "Michigan" },
  { code: "US-MN", name: "Minnesota" },
  { code: "US-MO", name: "Missouri" },
  { code: "US-MS", name: "Mississippi" },
  { code: "US-MT", name: "Montana" },
  { code: "US-NC", name: "North Carolina" },
  { code: "US-ND", name: "North Dakota" },
  { code: "US-NE", name: "Nebraska" },
  { code: "US-NH", name: "New Hampshire" },
  { code: "US-NJ", name: "New Jersey" },
  { code: "US-NM", name: "New Mexico" },
  { code: "US-NV", name: "Nevada" },
  { code: "US-NY", name: "New York" },
  { code: "US-OH", name: "Ohio" },
  { code: "US-OK", name: "Oklahoma" },
  { code: "US-OR", name: "Oregon" },
  { code: "US-PA", name: "Pennsylvania" },
  { code: "US-PR", name: "Puerto Rico" },
  { code: "US-RI", name: "Rhode Island" },
  { code: "US-SC", name: "South Carolina" },
  { code: "US-SD", name: "South Dakota" },
  { code: "US-TN", name: "Tenessee" },
  { code: "US-TX", name: "Texas" },
  { code: "US-UT", name: "Utah" },
  { code: "US-VA", name: "Virginia" },
  { code: "US-VI", name: "Virgin Islands" },
  { code: "US-VT", name: "Vermont" },
  { code: "US-WA", name: "Washington" },
  { code: "US-WI", name: "Wisconsin" },
  { code: "US-WV", name: "West Virginia" },
  { code: "US-WY", name: "Wyoming" },
  // {code:"-50",name:"Not Available, Temporarily"},
  // {code:"-70",name:"Asked, Unknown"},
  // {code:"-90",name:"Not Applicable"},
];

export const contactPurposeCT: CodeTableType[] = [
  //CT-014
  { code: "EC", name: "Emergency Contact" },
  { code: "NK", name: "Next of kin" },
  { code: "AS", name: "Administrative Staff" },
  { code: "CG", name: "Care Giver" },
  { code: "PA", name: "Power of Attorney" },
  { code: "IN", name: "Insurance" },
  { code: "GT", name: "Guarantor" },
  { code: "SDM", name: "Substitute Decision Maker" },
];

export const lifeStageCT: CodeTableType[] = [
  //CT-016
  { code: "N", name: "New born (birth - 28 days)" },
  { code: "I", name: "Infant (29 days < 2 years" },
  { code: "C", name: "Child (2 years - 15 years)" },
  { code: "T", name: "Adolescent (16 years - 17 years)" },
  { code: "A", name: "Adult (>= 18 years)" },
];

export const propertyOfOffendingAgentCT: CodeTableType[] = [
  { code: "DR", name: "Drug" },
  { code: "ND", name: "Non-drug" },
  { code: "UK", name: "Unknown" },
];

export const reactionTypeCT: CodeTableType[] = [
  { code: "AL", name: "Allergy" },
  { code: "AR", name: "Adverse Reaction" },
];

export const reactionSeverityCT: CodeTableType[] = [
  { code: "NO", name: "No Reaction" },
  { code: "MI", name: "Mild" },
  { code: "MO", name: "Moderate" },
  { code: "LT", name: "Severe Life Threatening" },
];

export const immunizationTypeCT: CodeTableType[] = [
  { code: "BCG", name: "Bacilius Calmette-Guerin" },
  { code: "Chol-O", name: "Cholera-Oral" },
  { code: "CholEcol", name: "Cholera, Entertoxogenic Escheria coli" },
  { code: "Chol-Ecol-O", name: "Cholera - E.coli - Oral" },
  { code: "DTaP", name: "Diphteria, Tetanus, Acellular Pertussis - pediatric" },
  {
    code: "DTaP-IPV",
    name: "Diphteria, Tetanus, Acellular Pertussis, Inactivated Polio - pediatric",
  },
  {
    code: "DTaP-IPV-Hib",
    name: "Diphteria, Tetanus, Acellular Pertussis, Inactivated Polio, Haemophilius influenzae type b - pediatric",
  },
  {
    code: "DTaP-IPV-Hib-HB",
    name: "Diphteria, Tetanus, Acellular Pertussis, Inactivated Polio, Haemophilius influenzae type b, Hepatitis B - pediatric",
  },
  {
    code: "DTaP-IPV-HB",
    name: "Diphteria, Tetanus, Acellular Pertussis, Inactivated Polio, Hepatitis B - pediatric",
  },
  {
    code: "DTaP-Hib",
    name: "Diphteria, Tetanus, Acellular Pertussis, Haemophilius influenzae type b - pediatric",
  },
  { code: "DT-IPV", name: "Diphteria, Tetanus, Polio - pediatric" },
  { code: "HA", name: "Hepatitis A" },
  { code: "HAHB", name: "Hepatitis A and B" },
  { code: "HA-Typh-I", name: "Hepatitis A and Typhoid - Injection" },
  { code: "HB", name: "Hepatitis B" },
  { code: "HB Tmf", name: "Hepatitis B - Thimerosal free" },
  { code: "Hib", name: "Haemophilius influenzae type b" },
  { code: "HPV", name: "Human Papilloma Virus" },
  { code: "Inf", name: "Influenza" },
  { code: "IPV", name: "Inactivated Polio" },
  { code: "JE", name: "Japanese Encephalitis" },
  { code: "Men", name: "Meningococcus" },
  { code: "Men B", name: "Neisseria Meningitidis Serogroup B Protein" },
  { code: "Men-C", name: "Meningococcal - Conjugate" },
  { code: "Men-P-AC", name: "Meningococcal - Polysaccharide" },
  { code: "Men-P-ACWY", name: "Meningococcal - Polysaccharide" },
  { code: "MMR", name: "Measles, Mumps, Rubella" },
  { code: "MMR-Var", name: "Measles, Mumps, Rubella, Varicella" },
  { code: "MR", name: "Measles, Rubella" },
  { code: "Pneu", name: "Pneumococcus" },
  { code: "Pneu-C-7", name: "Pneumococcal-Conjugate - valent" },
  { code: "Pneu-P-23", name: "Pneumococcal-Polysaccharide - valent" },
  { code: "Rab", name: "Rabies" },
  { code: "ROT", name: "Rotavirus - Oral" },
  { code: "T", name: "Tetanus" },
  { code: "Td", name: "Tetanus, Diphtheria - adult" },
  { code: "Tdap", name: "Tetanus, Diphtheria, Acellular Pertussis - adult" },
  {
    code: "TdapIPV",
    name: "Tetanus, Diptheria, Acellular Pertusis, Inactivated Poliomyelitis",
  },
  { code: "Td-IPV", name: "Tetanus, Diphtheria, Inactivated Polio - adult" },
  { code: "TBE", name: "Tickborne Encephalitis" },
  { code: "Typh", name: "Typhoid" },
  { code: "Typh-I", name: "Typhoid - Injection" },
  { code: "Typh-O", name: "Typhoid - Oral" },
  { code: "Typh (HA)", name: "Typhoid, Hepatitis A" },
  { code: "Var", name: "Varicella" },
  { code: "YF", name: "Yellow Fever" },
  { code: "Zos", name: "Herpes Zoster" },
];

export const prescriptionStatusCT: CodeTableType[] = [
  { code: "New", name: "New" },
  { code: "Active", name: "Active" },
  { code: "Suspended", name: "Suspended" },
  { code: "Aborted", name: "Aborted" },
  { code: "Completed", name: "Completed" },
  { code: "Obsolete", name: "Obsolete" },
  { code: "Nullified", name: "Nullified" },
];

export const ynIndicatorsimpleCT: CodeTableType[] = [
  { code: "Y", name: "Yes" },
  { code: "N", name: "No" },
];

export const treatmentTypesCT: CodeTableType[] = [
  { code: "CHRON", name: "Continuous/chronic" },
  { code: "ACU", name: "Acute" },
  { code: "ONET", name: "One Time" },
  { code: "PRN Long-term", name: "As needed (long-term)" },
  { code: "PRN Short-term", name: "As needed (short-term)" },
];

export const routeCT: CodeTableType[] = [
  { code: "BIN", name: "Block infiltration" },
  { code: "BUC", name: "Buccal" },
  { code: "CAU", name: "Caudal block" },
  { code: "CGY", name: "Cystourethrography" },
  { code: "DEN", name: "Dental" },
  { code: "DBR", name: "Disinfectant barn" },
  { code: "DCL", name: "Disinfectant contact lens" },
  { code: "DDC", name: "Disinfectant domestic" },
  { code: "DFP", name: "Disinfectant food" },
  { code: "DHO", name: "Disinfectant hospital area" },
  { code: "DII", name: "Disinfectant institutional" },
  { code: "DMI", name: "Disinfectant medical" },
  { code: "DIS", name: "Hemodialysis" },
  { code: "EPD", name: "Epidural" },
  { code: "ECP", name: "Extracorporeal" },
  { code: "EXT", name: "Extradural infusion" },
  { code: "EXVI", name: "Ex vivo" },
  { code: "INH", name: "Inhalation" },
  { code: "ISL", name: "Instillation" },
  { code: "IND", name: "Intervertebral" },
  { code: "IAM", name: "Intra amniotic" },
  { code: "IAR", name: "Intra arterial" },
  { code: "IA", name: "Intra articular" },
  { code: "IBR", name: "Intra bronchial" },
  { code: "IBU", name: "Intrabursal" },
  { code: "ICN", name: "Intracavernosal" },
  { code: "ICA", name: "Intracaudal" },
  { code: "ICE", name: "Intracerebral" },
  { code: "ITC", name: "Intracervical" },
  { code: "ICN", name: "Intracorneal" },
  { code: "ICO", name: "Intracoronary" },
  { code: "ICR", name: "Intracranial" },
  { code: "ICU", name: "Intracutaneous" },
  { code: "ICV", name: "Intracavity" },
  { code: "ID", name: "Intradermal" },
  { code: "IDI", name: "Intradiscal" },
  { code: "INF", name: "Intrafollicular" },
  { code: "IGA", name: "Intraganglional" },
  { code: "ITG", name: "Intragastric" },
  { code: "IL", name: "Intralesional" },
  { code: "IM", name: "Intramuscular" },
  { code: "IMM", name: "Intrammamary" },
  { code: "ITM", name: "Intramyocardial" },
  { code: "INMU", name: "Intramural" },
  { code: "ITN", name: "Intranasal" },
  { code: "ITNO", name: "Intranodal" },
  { code: "IO", name: "Intraocular" },
  { code: "IP", name: "Intraperitoneal" },
  { code: "IPL", name: "Intrapleural" },
  { code: "INP", name: "Intraprostatic" },
  { code: "IPU", name: "Intrapulmonary" },
  { code: "IPUT", name: "Intraputaminal" },
  { code: "IRU", name: "Intraruminal" },
  { code: "ISI", name: "Intrasinal" },
  { code: "ISP", name: "Intraspinal" },
  { code: "ISY", name: "Intrasynovial" },
  { code: "ITE", name: "Intratendinous" },
  { code: "ITS", name: "Intratesticular" },
  { code: "INT", name: "Intrathecal" },
  { code: "IT", name: "Intrathoracic" },
  { code: "ITR", name: "Intratracheal" },
  { code: "ITU", name: "Intratumor" },
  { code: "IU", name: "Intrauterine" },
  { code: "ITV", name: "Intravesicular" },
  { code: "IV", name: "Intravenous" },
  { code: "IVA", name: "Intravesical" },
  { code: "IVE", name: "Intravertebral" },
  { code: "IVL", name: "Intravitreal" },
  { code: "IVR", name: "Intraventricular" },
  { code: "IR", name: "Irrigation" },
  { code: "MIS", name: "Miscellaneous" },
  { code: "NAS", name: "Nasal" },
  { code: "NEB", name: "Nebulizer" },
  { code: "OPH", name: "Ophtalmic" },
  { code: "ORL", name: "Oral" },
  { code: "OT", name: "Otic (auricular)" },
  { code: "PCU", name: "Percutaneous" },
  { code: "PRB", name: "Peribular block" },
  { code: "PRS", name: "Periosteal" },
  { code: "PRT", name: "Parenteral unspecified" },
  { code: "RB", name: "Retrobulbar" },
  { code: "RT", name: "Rectal" },
  { code: "ST", name: "Soft tissue" },
  { code: "SAR", name: "Subrarachnoidal" },
  { code: "SC", name: "Subcutaneous" },
  { code: "SGV", name: "Subgingival" },
  { code: "SLG", name: "Sublingual" },
  { code: "TDP", name: "Teat dip" },
  { code: "TOP", name: "Topical" },
  { code: "TRD", name: "Transdermal" },
  { code: "TRU", name: "Transurethral" },
  { code: "UNS", name: "Unassigned" },
  { code: "URH", name: "Urethral" },
  { code: "UWH", name: "Udder wash" },
  { code: "VAG", name: "Vaginal" },
];

export const formCT: CodeTableType[] = [
  { code: "AEM", name: "Aerosol metered-dose" },
  { code: "AER", name: "Aerosol with propellants" },
  { code: "BAR", name: "Bar chewable" },
  { code: "BEA", name: "Bead" },
  { code: "BIS", name: "Biscuit" },
  { code: "BLS", name: "Bolus" },
  { code: "CAP", name: "Capsule" },
  { code: "CART", name: "Cartridge" },
  { code: "CDR", name: "Capsule delayed release" },
  { code: "CMT", name: "Cement" },
  { code: "COR", name: "Cord" },
  { code: "CRM", name: "Cream" },
  { code: "DCH", name: "Douche" },
  { code: "DPS", name: "Drops" },
  { code: "DRE", name: "Dressing" },
  { code: "ECC", name: "Capsule enteric-coated" },
  { code: "ECT", name: "Tablet enteric coated" },
  { code: "ELX", name: "Elixir" },
  { code: "EML", name: "Emulsion" },
  { code: "ENM", name: "Enema" },
  { code: "EVT", name: "Tablet effervescent" },
  { code: "FLS", name: "Floss" },
  { code: "GAS", name: "Gas" },
  { code: "GDR", name: "Granule for suspension" },
  { code: "GEF", name: "Granule effervescent" },
  { code: "GEL", name: "Gel" },
  { code: "GER", name: "Gel controlled release" },
  { code: "GLO", name: "Globules" },
  { code: "GRA", name: "Granules" },
  { code: "GRT", name: "Graft" },
  { code: "GUM", name: "Gum chewable" },
  { code: "IMP", name: "Implant" },
  { code: "INS", name: "Insert" },
  { code: "IER", name: "Insert extended release" },
  { code: "JAM", name: "Jam" },
  { code: "KIT", name: "Kit" },
  { code: "LEF", name: "Leaf" },
  { code: "LIP", name: "Liposome" },
  { code: "LIQ", name: "Liquid" },
  { code: "LOT", name: "Lotion" },
  { code: "LOZ", name: "Lozenge" },
  { code: "MWH", name: "Mouthwash gargle" },
  { code: "ONT", name: "Ointment" },
  { code: "OVU", name: "Ovules" },
  { code: "PAD", name: "Pad" },
  { code: "PATCH", name: "Patch" },
  { code: "PEC", name: "Powder enteric coated" },
  { code: "PEF", name: "Powder effervescent" },
  { code: "PEN", name: "Pencil" },
  { code: "PIC", name: "Piece chewable" },
  { code: "PLS", name: "Plaster" },
  { code: "PMD", name: "Metered dose pump" },
  { code: "PMX", name: "Drug premix" },
  { code: "POR", name: "Pellet (oral)" },
  { code: "POW", name: "Powder" },
  { code: "PSS", name: "Powder sustained release" },
  { code: "PSSR", name: "Powder for suspension" },
  { code: "PST", name: "Paste" },
  { code: "PSU", name: "Powder for suspension" },
  { code: "PWSO", name: "Powder for solution" },
  { code: "RING", name: "Ring slow release" },
  { code: "SDR", name: "Suspension delayed" },
  { code: "SHP", name: "Shampoo" },
  { code: "SMD", name: "Spray metered dose" },
  { code: "SOL", name: "Solution" },
  { code: "SHP", name: "Shampoo" },
  { code: "SOP", name: "Soap bar" },
  { code: "SPCAP", name: "Sprinkle capsule" },
  { code: "SPG", name: "Sponge" },
  { code: "SPR", name: "Spray" },
  { code: "SPS", name: "Suppository sutained" },
  { code: "SRC", name: "Sustained release" },
  { code: "SRD", name: "Disc sustained release" },
  { code: "SRS", name: "Syrup sustained release" },
  { code: "SRT", name: "Sustained release tablet" },
  { code: "STK", name: "Stick" },
  { code: "STP", name: "Strip" },
  { code: "SUP", name: "Suppository" },
  { code: "SUS", name: "Suspension" },
  { code: "SUT", name: "Suture" },
  { code: "SWA", name: "Swab" },
  { code: "SYR", name: "Syrup" },
  { code: "TAB", name: "Tablet" },
  { code: "TABC", name: "Tablet chewable" },
  { code: "TDIS", name: "Tablet dispersible" },
  { code: "TDR", name: "Tablet delayed release" },
  { code: "TRD", name: "Tablet rapid dissolve" },
  { code: "SLT", name: "Tablet sublingual" },
  { code: "TAP", name: "Tape" },
  { code: "TDL", name: "Teat dilator" },
  { code: "TEA", name: "Tea herbal" },
  { code: "TPT", name: "Toothpaste" },
  { code: "UNS", name: "Unassigned" },
  { code: "WAF", name: "Wafer" },
  { code: "WIP", name: "Wipe" },
];

export const frequencyCT: CodeTableType[] = [
  { code: "QD", name: "Once a day" },
  { code: "BID", name: "Two times a day" },
  { code: "TID", name: "Three times a day" },
  { code: "QID", name: "Four times a day" },
  { code: "QAM", name: "Every morning" },
  { code: "QNOON", name: "Once a day, at noon" },
  { code: "QPM", name: "Once a day, in the" },
  { code: "QHS", name: "Once a day, at night" },
  { code: "Q1H", name: "Every hour" },
  { code: "Q1-2H", name: "Every 1-2 hours" },
  { code: "Q2H", name: "Every 2 hours" },
  { code: "Q2-3H", name: "Every 2-3 hours" },
  { code: "Q3H", name: "Every 3 hours" },
  { code: "Q3-4H", name: "Every 3-4 hours" },
  { code: "Q4H", name: "Every 4 hours" },
  { code: "Q4-6H", name: "Every 4 to 6 hours" },
  { code: "Q6H", name: "Every 6 hours" },
  { code: "Q6-8H", name: "Every 6 to 8 hours" },
  { code: "Q8H", name: "Every 8 hours" },
  { code: "Q8-12H", name: "Every 8 to 12 hours" },
  { code: "Q12H", name: "Every 12 hours" },
  { code: "Q2D", name: "Every 2 days" },
  { code: "1/week", name: "Once a week" },
  { code: "2/week", name: "Twice a week" },
  { code: "1/5day", name: "Once every 5 days" },
  { code: "1/6day", name: "Once every 6 days" },
  { code: "21/28D", name: "21 out of 28 days" },
  { code: "1/month", name: "Once a month" },
  { code: "ONCE", name: "A single dose" },
  { code: "OTH", name: "Other" },
  { code: "PRN", name: "as needed" },
];

export const strengthUnitCT: CodeTableType[] = [
  { code: "AMP", name: "Ampoule" },
  { code: "AU", name: "Allergy unit" },
  { code: "B", name: "Billion" },
  { code: "BATCH", name: "Batch" },
  { code: "BLD", name: "Blister" },
  { code: "BOTTL", name: "Bottle" },
  { code: "BOX", name: "Box" },
  { code: "C", name: "Centesimal dilution" },
  { code: "CAN", name: "Can" },
  { code: "CAP", name: "Capsule" },
  { code: "CART", name: "Cartridge" },
  { code: "CC", name: "Cubic centimetre" },
  { code: "CCA", name: "Chimpanze coryza" },
  { code: "CELLS", name: "Cells" },
  { code: "CH", name: "Centesimal" },
  { code: "CM", name: "Centimetre" },
  { code: "D", name: "Decimal dilution" },
  { code: "DAY", name: "Day" },
  { code: "DH", name: "Decimal hahnemannian" },
  { code: "DISK", name: "Disk" },
  { code: "DOSE", name: "Dose" },
  { code: "DROP", name: "Drop" },
  { code: "DU", name: "Deca unit" },
  { code: "FL DR", name: "Fluid dram" },
  { code: "FL OZ", name: "Fluid ounce" },
  { code: "GAL", name: "Gallon" },
  { code: "GBQ", name: "Gigabecquerel" },
  { code: "GM", name: "Gram" },
  { code: "GR", name: "Grain" },
  { code: "HR", name: "Hour" },
  { code: "IMP", name: "Implant" },
  { code: "INS", name: "Insert" },
  { code: "JAR", name: "Jar" },
  { code: "K", name: "Homepathic 1:1000" },
  { code: "KG", name: "Kilogram" },
  { code: "KIT", name: "Kit" },
  { code: "L", name: "Litre" },
  { code: "LB", name: "Pound" },
  { code: "LF", name: "Limit flocculation unit" },
  { code: "LOZ", name: "Lozenge" },
  { code: "M", name: "Million" },
  { code: "MBQ", name: "Megabecquerel" },
  { code: "MC", name: "Millicurie" },
  { code: "MCC", name: "Microcurie" },
  { code: "MCG", name: "Microgram" },
  { code: "MCL", name: "Microlitres" },
  { code: "MEQ", name: "Milliequivalent" },
  { code: "MG", name: "Milligram" },
  { code: "ML", name: "Millilitre" },
  { code: "MMO", name: "Millimole" },
  { code: "NGM", name: "Nanogram" },
  { code: "NIL", name: "NIL" },
  { code: "NKAT", name: "Nanokat" },
  { code: "NS", name: "Non-standard" },
  { code: "OZ", name: "Ounce" },
  { code: "PAD", name: "Pad" },
  { code: "PATCH", name: "Patch" },
  { code: "PCK", name: "Package" },
  { code: "PER", name: "Percentage" },
  { code: "PIECE", name: "Piece" },
  { code: "PPM", name: "Parts per million" },
  { code: "PPU", name: "Pertussis protective unit" },
  { code: "PRTV", name: "Particles viral" },
  { code: "PNU", name: "Protein nitrogen unit" },
  { code: "QS", name: "Quantity sufficient" },
  { code: "RING", name: "Ring" },
  { code: "SPG", name: "Sponge" },
  { code: "SPR", name: "Spray" },
  { code: "SQ CM", name: "Square centimetre" },
  { code: "SQ IN", name: "Square inch" },
  { code: "STRIP", name: "Strip" },
  { code: "SUP", name: "Suppository" },
  { code: "SYR", name: "Syringe" },
  { code: "TAB", name: "Tablet" },
  { code: "TBS", name: "Tablespoon" },
  { code: "TM", name: "Mother-tincture" },
  { code: "TRACE", name: "Trace" },
  { code: "TRU", name: "Turbidity reducing unit" },
  { code: "TUB", name: "Tuberculin unit" },
  { code: "UNIT", name: "International unit" },
  { code: "VIAL", name: "Vial" },
  { code: "WAF", name: "Wafer" },
  { code: "X", name: "Homeopathic unit" },
];

export const dosageUnitCT: CodeTableType[] = [
  { code: "tsp", name: "teaspoon" },
  { code: "tbls", name: "tablespoon" },
  { code: "puff", name: "puff" },
  { code: "dps", name: "drops" },
  { code: "loz", name: "lozenge" },
  { code: "puffs", name: "puffs" },
  { code: "sup", name: "suppositories" },
  { code: "tab", name: "tablet" },
  { code: "cap", name: "capsule" },
  { code: "tsp", name: "teaspoon" },
  { code: "ovu", name: "ovules" },
  { code: "mg", name: "milligram" },
  { code: "g", name: "gram" },
  { code: "mcg", name: "microgram" },
  { code: "K", name: "Homeopathic 1:1000" },
  { code: "L", name: "Litre" },
  { code: "mL", name: "milliliter" },
  { code: "mcL", name: "microliter" },
];

export const siteCT: CodeTableType[] = [
  { code: "LVL", name: "Left Vasus Lateralis" },
  { code: "RVL", name: "Right Vasus Lateralis" },
  { code: "LD", name: "Left Deltoid" },
  { code: "RD", name: "Right Deltoid" },
  { code: "LALT", name: "Left AnteroLateral fat of" },
  { code: "RALT", name: "Right AnteroLateral fat of" },
  { code: "LPUA", name: "Left PosteroLateral fat of" },
  { code: "RPUA", name: "Right PosteroLateral fat of" },
  { code: "LFA", name: "Left ForeArm" },
  { code: "RFA", name: "Right ForeArm" },
];

export const reportFormatCT: CodeTableType[] = [
  { code: "Text", name: "Text" },
  { code: "Binary", name: "Binary" },
];

export const reportClassCT: CodeTableType[] = [
  { code: "Diagnostic Imaging Report", name: "Diagnostic Imaging Report" },
  { code: "Diagnostic Test Report", name: "Diagnostic Test Report" },
  { code: "Cardio Respiratory Report", name: "Cardio Respiratory Report" },
  { code: "Medical Records Report", name: "Medical Records Report" },
  { code: "Consultant Report", name: "Consultant Report" },
  { code: "Lab Report", name: "Lab Report" },
  { code: "Other Letter", name: "Other Letter" },
];

export const reportMediaCT: CodeTableType[] = [
  { code: "Email", name: "Email" },
  { code: "Download", name: "Download" },
  { code: "Portable Media", name: "Portable Media" },
  { code: "Hardcopy", name: "Hardcopy" },
];

export const terminationReasonCT = [
  { code: "12", name: "Health Number error" },
  { code: "14", name: "Patient identified as deceased on ministry database" },
  { code: "24", name: "Patient added to roster in error" },
  {
    code: "30",
    name: "Pre-member/ Assigned member ended; now enrolled or registered with red and white health card",
  },
  {
    code: "32",
    name: "Pre-member/ Assigned member ended; now enrolled or registered with photo health card",
  },
  {
    code: "33",
    name: "Termination reason cannot be released (due to patient confidentiality)",
  },
  { code: "35", name: "Patient transferred from roster per physician request" },
  { code: "36", name: "Original enrolment ended; patient now re-enroled" },
  {
    code: "37",
    name: "Original enrolment ended; patient now enrolled as Long Term Care",
  },
  {
    code: "38",
    name: "Long Term Care enrolment ended; patient has left Long Term Care",
  },
  {
    code: "39",
    name: "Assigned member status ended; roster transferred per physician request",
  },
  { code: "40", name: "Physician reported member as deceased" },
  {
    code: "41",
    name: "Patient no longer meets selection criteria for your roster – assigned to another physician",
  },
  {
    code: "42",
    name: "Physician ended enrolment; patient entered Long Term Care facility",
  },
  { code: "44", name: "Physician ended patient enrolment" },
  {
    code: "51",
    name: "Patient no longer meets selection criteria for your roster",
  },
  {
    code: "53",
    name: "Physician ended enrolment; patient moved out of geographic area",
  },
  { code: "54", name: "Physician ended enrolment; patient left province" },
  { code: "56", name: "Physician ended enrolment; per patient request" },
  { code: "57", name: "Enrolment terminated by patient" },
  { code: "59", name: "Enrolment ended; patient out of geographic area" },
  { code: "60", name: "No current eligibility" },
  {
    code: "61",
    name: "Patient out of geographic area; address over-ride applied",
  },
  {
    code: "62",
    name: "Patient out of geographic area; address over-ride removed",
  },
  { code: "73", name: "No current eligibility" },
  { code: "74", name: "No current eligibility" },
  { code: "82", name: "Ministry has not received enrolment/ Consent form" },
  {
    code: "84",
    name: "Termination reason cannot be released (due to patient confidentiality)",
  },
  {
    code: "90",
    name: "Termination reason cannot be released (due to patient confidentiality)",
  },
  {
    code: "91",
    name: "Termination reason cannot be released (due to patient confidentiality)",
  },
];

export const diabetesComplicationsScreeningCT: CodeTableType[] = [
  { code: "32468-1", name: "Retinal Exam" },
  { code: "11397-7", name: "Foot Exam" },
  { code: "67536-3", name: "Neurological Exam" },
];
export const diabetesMotivationalCounsellingCT: CodeTableType[] = [
  { code: "Nutrition", name: "Nutrition" },
  { code: "Exercise", name: "Exercise" },
  { code: "Smoking Cessation", name: "Smoking Cessation" },
  { code: "Other", name: "Others" },
];

export const toCodeTableName = (codeTable: CodeTableType[], code?: string) => {
  if (!code) return "";
  return codeTable.find((item) => item.code === code)?.name || "";
};
